version: '3.8'

services:
  postgres_db:
    container_name: postgres_container
    image: postgres:16.0
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "15432:5432"
    networks:
      - postgres-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres-network
    restart: unless-stopped

  flyway:
    image: flyway/flyway
    command: migrate
    depends_on:
      - postgres_db
    networks:
      - postgres-network
    environment:
      - FLYWAY_URL=${POSTGRES_URL}
      - FLYWAY_USER=${POSTGRES_USERNAME}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}


networks:
  postgres-network:
    driver: bridge

volumes:
  postgres:
  pgadmin: