spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true

  flyway:
    url: ${POSTGRES_URL}
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    locations: classpath:db/migration
    clean-on-validation-error: true
    clean-disabled: false
    baseline-on-migrate: true
    baseline-version: 0